packages:
  - backend
  - frontend
  - packages/*
  - apps/*
  - apps/**
  - codex-extensions
  - '!packages/codex-viewer/**'
  - '!apps/frame.dev/packages/codex-viewer/**'

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - better-sqlite3
  - esbuild
  - unrs-resolver
  - vue-demi
