packages:
  - backend
  - frontend
  - packages/*
  - apps/*
  - codex-extensions

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - better-sqlite3
  - esbuild
  - unrs-resolver
  - vue-demi
