// backend/agentos/api/types/AgentOSResponse.ts

import {
  ToolCall,
  AudioOutputConfig,
  ImageOutputConfig,
  UICommand,
  ReasoningTrace,
  CostAggregator,
  ConversationContext, // Import for final output, if context is fully sent
} from '../../cognitive_substrate/IGMI';
import { IPersonaDefinition } from '../../cognitive_substrate/personas/IPersonaDefinition'; // For persona details in final output

/**
 * @fileoverview Defines the unified streaming output structure for the AgentOS API.
 * This interface allows for real-time delivery of text deltas, tool call requests,
 * system progress, and final comprehensive responses from the AgentOS.
 * @module backend/agentos/api/types/AgentOSResponse
 */

/**
 * @enum {string} AgentOSResponseChunkType
 * Defines the distinct types of chunks that can be streamed from the AgentOS.
 * This allows the frontend or consuming service to interpret and handle each
 * piece of the streaming response appropriately.
 */
export enum AgentOSResponseChunkType {
  /** Indicates a delta of text content for the primary response. */
  TEXT_DELTA = 'text_delta',
  /** Signals that the AgentOS is performing an internal operation or progress update. */
  SYSTEM_PROGRESS = 'system_progress',
  /** Indicates that the agent has decided to call one or more tools. */
  TOOL_CALL_REQUEST = 'tool_call_request',
  /** Provides the result of a previously executed tool call. */
  TOOL_RESULT_EMISSION = 'tool_result_emission',
  /** Signals a dynamic UI command that the frontend should render or execute. */
  UI_COMMAND = 'ui_command',
  /** The final and complete output for the turn, including all accumulated data. */
  FINAL_RESPONSE = 'final_response',
  /** An error occurred during processing, potentially terminating the stream. */
  ERROR = 'error',
  /** A metadata update without new content. */
  METADATA_UPDATE = 'metadata_update',
}

/**
 * @typedef {Object} AgentOSResponseChunk
 * The base interface for any chunk received from the AgentOS streaming API.
 * All chunks share common metadata to maintain context.
 * @property {AgentOSResponseChunkType} type - The specific type of this streaming chunk.
 * @property {string} streamId - A unique identifier for the entire logical stream/turn.
 * This ID links all chunks belonging to the same interaction.
 * @property {string} gmiInstanceId - The ID of the GMI instance that generated this chunk.
 * @property {string} personaId - The ID of the persona (agent) currently active for this stream.
 * @property {boolean} isFinal - If `true`, this is the last chunk for the `streamId` and
 * the stream will close shortly after.
 */
export interface AgentOSResponseChunk {
  type: AgentOSResponseChunkType;
  streamId: string;
  gmiInstanceId: string;
  personaId: string;
  isFinal: boolean;
  // Common metadata for all chunks
  timestamp: string;
  metadata?: Record<string, any>;
}

/**
 * @typedef {Object} AgentOSTextDeltaChunk
 * Represents a piece of textual response generated by the agent.
 * @augments {AgentOSResponseChunk}
 * @property {AgentOSResponseChunkType.TEXT_DELTA} type
 * @property {string} textDelta - The incremental text content to append to the response.
 */
export interface AgentOSTextDeltaChunk extends AgentOSResponseChunk {
  type: AgentOSResponseChunkType.TEXT_DELTA;
  textDelta: string;
}

/**
 * @typedef {Object} AgentOSSystemProgressChunk
 * Provides updates on the internal progress of the AgentOS.
 * @augments {AgentOSResponseChunk}
 * @property {AgentOSResponseChunkType.SYSTEM_PROGRESS} type
 * @property {string} message - A human-readable message describing the progress.
 * @property {number} [progressPercentage] - Optional percentage indicating overall progress.
 * @property {string} [statusCode] - Optional code for programmatic interpretation of status.
 */
export interface AgentOSSystemProgressChunk extends AgentOSResponseChunk {
  type: AgentOSResponseChunkType.SYSTEM_PROGRESS;
  message: string;
  progressPercentage?: number;
  statusCode?: string;
}

/**
 * @typedef {Object} AgentOSToolCallRequestChunk
 * Informs the client that the agent has decided to call one or more tools.
 * The client is expected to acknowledge or initiate tool execution (if external).
 * @augments {AgentOSResponseChunk}
 * @property {AgentOSResponseChunkType.TOOL_CALL_REQUEST} type
 * @property {ToolCall[]} toolCalls - An array of tool calls requested by the agent.
 * @property {string} [rationale] - An optional explanation from the agent about why these tools are being called.
 */
export interface AgentOSToolCallRequestChunk extends AgentOSResponseChunk {
  type: AgentOSResponseChunkType.TOOL_CALL_REQUEST;
  toolCalls: ToolCall[];
  rationale?: string;
}

/**
 * @typedef {Object} AgentOSToolResultEmissionChunk
 * Provides the client with the result of a tool call that was previously requested.
 * This is typically emitted after an external tool execution completes and its
 * result is fed back to the GMI.
 * @augments {AgentOSResponseChunk}
 * @property {AgentOSResponseChunkType.TOOL_RESULT_EMISSION} type
 * @property {string} toolCallId - The ID of the tool call this result pertains to.
 * @property {string} toolName - The name of the tool that was executed.
 * @property {any} toolResult - The raw result object from the tool execution.
 * @property {boolean} isSuccess - Indicates if the tool execution was successful.
 * @property {string} [errorMessage] - If not successful, an error message.
 */
export interface AgentOSToolResultEmissionChunk extends AgentOSResponseChunk {
  type: AgentOSResponseChunkType.TOOL_RESULT_EMISSION;
  toolCallId: string;
  toolName: string;
  toolResult: any; // Could be { data: any } or { error: { message: string, details?: any } }
  isSuccess: boolean;
  errorMessage?: string;
}


/**
 * @typedef {Object} AgentOSUICommandChunk
 * Contains instructions for the frontend to render or update dynamic UI components.
 * @augments {AgentOSResponseChunk}
 * @property {AgentOSResponseChunkType.UI_COMMAND} type
 * @property {UICommand[]} uiCommands - An array of UI commands to be executed by the client.
 */
export interface AgentOSUICommandChunk extends AgentOSResponseChunk {
  type: AgentOSResponseChunkType.UI_COMMAND;
  uiCommands: UICommand[];
}

/**
 * @typedef {Object} AgentOSFinalResponseChunk
 * The final, comprehensive output for a given turn. This chunk aggregates all
 * information (text, tool calls, costs, reasoning) and signals the end of the stream.
 * @augments {AgentOSResponseChunk}
 * @property {AgentOSResponseChunkType.FINAL_RESPONSE} type
 * @property {string} finalResponseText - The complete and final textual response.
 * @property {ToolCall[]} [finalToolCalls] - Any tool calls that are part of the final decision (e.g., if LLM's final response is a tool call).
 * @property {UICommand[]} [finalUiCommands] - Any UI commands meant to be rendered or executed at the very end.
 * @property {AudioOutputConfig} [audioOutput] - Configuration for any final audio output (e.g., TTS).
 * @property {ImageOutputConfig} [imageOutput] - Data for any generated image output.
 * @property {CostAggregator} [usage] - Aggregated token usage and cost for the entire turn.
 * @property {ReasoningTrace[]} [reasoningTrace] - A detailed trace of the agent's internal reasoning steps (if debug mode is enabled).
 * @property {Error} [error] - Any critical error that prevented a successful completion.
 * @property {ConversationContext} [updatedConversationContext] - The full, updated conversation context at the end of the turn.
 * Useful for client-side state synchronization, especially after tool calls.
 * @property {IPersonaDefinition} [activePersonaDetails] - Details of the persona that was active for this turn.
 */
export interface AgentOSFinalResponseChunk extends AgentOSResponseChunk {
  type: AgentOSResponseChunkType.FINAL_RESPONSE;
  finalResponseText: string | null; // Can be null if only tool calls or UI commands
  finalToolCalls?: ToolCall[];
  finalUiCommands?: UICommand[];
  audioOutput?: AudioOutputConfig;
  imageOutput?: ImageOutputConfig;
  usage?: CostAggregator;
  reasoningTrace?: ReasoningTrace[];
  error?: { code: string; message: string; details?: any };
  updatedConversationContext?: ConversationContext;
  activePersonaDetails?: Partial<IPersonaDefinition>; // Send only necessary public details
}

/**
 * @typedef {Object} AgentOSErrorChunk
 * Signals that an error occurred, potentially leading to stream termination.
 * @augments {AgentOSResponseChunk}
 * @property {AgentOSResponseChunkType.ERROR} type
 * @property {string} code - A unique error code for programmatic handling.
 * @property {string} message - A human-readable error message.
 * @property {any} [details] - Optional additional details about the error.
 */
export interface AgentOSErrorChunk extends AgentOSResponseChunk {
  type: AgentOSResponseChunkType.ERROR;
  code: string;
  message: string;
  details?: any;
}

/**
 * @typedef {Object} AgentOSMetadataUpdateChunk
 * Provides updates on metadata relevant to the session or GMI without
 * new content or progress messages. Useful for adapting client state.
 * @augments {AgentOSResponseChunk}
 * @property {AgentOSResponseChunkType.METADATA_UPDATE} type
 * @property {Record<string, any>} updates - A map of metadata keys to their new values.
 */
export interface AgentOSMetadataUpdateChunk extends AgentOSResponseChunk {
  type: AgentOSResponseChunkType.METADATA_UPDATE;
  updates: Record<string, any>;
}

/**
 * @typedef {AgentOSTextDeltaChunk | AgentOSSystemProgressChunk | AgentOSToolCallRequestChunk | AgentOSToolResultEmissionChunk | AgentOSUICommandChunk | AgentOSFinalResponseChunk | AgentOSErrorChunk | AgentOSMetadataUpdateChunk} AgentOSResponse
 * Union type representing any possible chunk that can be streamed from AgentOS.
 */
export type AgentOSResponse =
  | AgentOSTextDeltaChunk
  | AgentOSSystemProgressChunk
  | AgentOSToolCallRequestChunk
  | AgentOSToolResultEmissionChunk
  | AgentOSUICommandChunk
  | AgentOSFinalResponseChunk
  | AgentOSErrorChunk
  | AgentOSMetadataUpdateChunk;