FROM node:20-alpine
WORKDIR /app
COPY ../../pnpm-lock.yaml ../../package.json ../../pnpm-workspace.yaml ./
RUN npm install -g pnpm && pnpm install --frozen-lockfile
COPY . .
EXPOSE 3000
CMD ["pnpm", "dev"]
