// backend/agentos/core/conversation/ConversationMessage.ts

import { SentimentResult } from '../ai_utilities/IUtilityAI'; // Assuming path is correct

/**
 * @fileoverview Defines the robust and detailed structure for a single message within a conversation
 * in AgentOS, suitable for complex interactions including tool usage, rich content embedding,
 * user feedback, and comprehensive metadata for analytics and adaptive behavior.
 * @module agentos/core/conversation/ConversationMessage
 */

/**
 * Represents the role of the entity that produced the message.
 * This enum is critical for how LLMs interpret the flow of conversation and for system logic.
 */
export enum MessageRole {
  /** Instructions, context, or persona definitions provided by the system/developer. Often hidden from the end-user during normal display. */
  SYSTEM = 'system',
  /** Input directly from the end-user. */
  USER = 'user',
  /** Responses generated by an AI agent or model. */
  ASSISTANT = 'assistant',
  /** Results or outputs from a tool execution, responding to an assistant's tool_call. */
  TOOL = 'tool',
  /**
   * A message representing a summarized block of older messages.
   * This role is used internally by components like the PromptEngine to manage context length
   * while preserving key information from earlier parts of the conversation.
   */
  SUMMARY = 'summary',
  /**
   * Represents an error message, either from the system or an agent, intended for user display
   * or internal logging, distinct from a normal assistant response.
   */
  ERROR = 'error',
  /**
   * Represents an agent's internal "thought" or intermediate reasoning step.
   * Typically not shown to the user but logged for debugging or used for self-correction.
   */
  THOUGHT = 'thought',
}

/**
 * Represents a request from an 'assistant' message to call one or more tools/functions.
 * This structure is designed to be compatible with OpenAI's function calling and adaptable for other models.
 */
export interface ToolCallRequest {
  /** A unique identifier for this specific tool call, generated by the assistant. Used to match with tool responses. */
  id: string;
  /** The type of the tool to be called, typically 'function' for most current LLM implementations. */
  type: 'function';
  /** Contains the name and arguments of the function to be called. */
  function: {
    /** The name of the function/tool to be invoked (must match a registered tool). */
    name: string;
    /**
     * A JSON string representing the arguments to pass to the function.
     * The tool executor is responsible for parsing this string.
     */
    arguments: string;
  };
}

/**
 * Optional, extensive metadata associated with a message, allowing for rich analytics,
 * feedback processing, and adaptive system behavior.
 */
export interface MessageMetadata {
  /** If the message content was modified (e.g., truncated, summarized), provides details. */
  modificationInfo?: {
    strategy: 'truncated' | 'summarized' | 'filtered';
    originalTokenCount?: number;
    finalTokenCount?: number;
    originalLengthChars?: number; // Character length before modification
    originalMessageCount?: number; // If this message is a summary of multiple messages
    reason?: string; // Reason for modification
  };
  /** Calculated token count of the `content` field, if available. */
  tokenCount?: number;
  /** Detected language code of the message content (e.g., 'en', 'es', 'fr-CA'). */
  language?: string;
  /** Confidence score for the detected language (0-1). */
  languageConfidence?: number;
  /** Sentiment analysis result for the message content. */
  sentiment?: SentimentResult;
  /** Source or channel of the message (e.g., 'direct_text_input', 'transcribed_audio_whisper', 'tool_web_search_result', 'agent_xyz_response'). */
  source?: string;
  /** User feedback on the message (e.g., 'thumbs_up', 'thumbs_down', numerical rating, textual feedback ID). */
  userFeedback?: {
    rating?: 'positive' | 'negative' | 'neutral' | number;
    feedbackTextId?: string; // Link to more detailed feedback
    tags?: string[];
  };
  /** Custom tags or keywords for categorization, filtering, or routing. */
  customTags?: string[];
  /**
   * Controls the visibility or processing of the message.
   * 'user': Visible to the end-user.
   * 'developer_log': For debugging and development logs, not typically shown to users.
   * 'system_internal': For internal AgentOS processing, potentially hidden even from developers unless in verbose mode.
   * 'agent_memory': Indicates the message is primarily for an agent's internal memory or thought process.
   */
  visibility?: 'user' | 'developer_log' | 'system_internal' | 'agent_memory';
  /** If this message is a response to a specific previous message, its ID. Useful for threading or quoting. */
  inReplyToMessageId?: string;
  /** If the message was generated by a specific agent persona or sub-agent. */
  agentPersonaId?: string;
  /** Current mood of the agent when this message was generated (if applicable). */
  agentMood?: string;
  /** Confidence score of the AI generating this message (if applicable and provided by the model). */
  generationConfidence?: number;
  /** Indicates if this message (or parts of it) should be considered for long-term memory. */
  storeInLongTermMemory?: boolean;
  /** Alternative representations of the content, e.g., SSML for speech, or a direct audio URL. */
  alternativeRepresentations?: {
    ssml?: string; // For text-to-speech generation
    audioUrl?: string; // If audio was generated and stored
    displayText?: string; // If 'content' is complex (e.g. structured data), this is for clean UI display
  };
  /** For messages of role `SUMMARY`, this indicates the IDs of the messages that were summarized. */
  summarizedMessageIds?: string[];
  /** Any other custom key-value pairs for extensibility, allowing application-specific data. */
  [key: string]: any;
}

/**
 * @interface ConversationMessage
 * Represents a single, comprehensive message within a conversation.
 * This structure is designed to be compatible with and extend common chat model API formats,
 * while providing rich metadata for advanced AgentOS functionalities including state export.
 */
export interface ConversationMessage {
  /**
   * A unique, immutable identifier for this message within the entire system (e.g., UUID v4).
   * Essential for tracking, referencing, storage, and state export.
   */
  readonly id: string;

  /**
   * The role of the message sender, determining its interpretation in the conversation flow.
   */
  role: MessageRole;

  /**
   * The primary textual content of the message.
   * - Can be `null` for `assistant` messages that *only* contain `tool_calls`.
   * - For `MessageRole.SUMMARY`, this holds the summarized text.
   * - For `MessageRole.ERROR`, this holds the error message.
   * - For `MessageRole.THOUGHT`, this holds the agent's internal thought process.
   */
  content: string | null;

  /**
   * Timestamp of when the message was created or officially logged (Unix epoch in milliseconds).
   * Ensures chronological ordering and aids in analytics and state reconstruction.
   */
  readonly timestamp: number;

  /**
   * Optional. The name of the author or entity associated with this message.
   * - For `role: MessageRole.TOOL`, this **must** be the `toolId` of the tool that produced the content.
   * - For `role: MessageRole.ASSISTANT`, this could be the `agentId` or a specific persona name.
   * - For `role: MessageRole.USER`, this could be a `userId`.
   */
  name?: string;

  // --- Fields primarily for Assistant and Tool interactions (OpenAI compatible) ---
  /**
   * Optional. For `role: MessageRole.ASSISTANT` messages.
   * An array of tool calls requested by the assistant.
   */
  tool_calls?: ToolCallRequest[];

  /**
   * Optional. For `role: MessageRole.TOOL` messages.
   * The unique identifier of the `ToolCallRequest` (from an assistant's `tool_calls` array)
   * that this tool message is a response to. **Required if role is TOOL.**
   */
  tool_call_id?: string;

  // --- Additional rich information ---
  /**
   * Optional. For messages with `role: MessageRole.SUMMARY`.
   * Indicates how many original messages this summary condenses.
   */
  originalMessagesSummarizedCount?: number;

  /**
   * Optional. A flexible metadata object for storing additional information
   * related to the message. This is crucial for advanced features, personalization,
   * analytics, and comprehensive state export.
   */
  metadata?: MessageMetadata;
}