// backend/services/ui_action_orchestration/IUIActionOrchestratorService.ts

/**
 * Defines the structure for a UI command that the frontend can interpret.
 * This schema should be designed with your Tailwind CSS frontend components in mind.
 */
export interface FrontendUICommand {
  /** A unique ID for this command instance. */
  commandId: string;
  /** The type of UI action to perform. */
  actionType: 'RENDER_DYNAMIC_BLOCK' | 'UPDATE_DYNAMIC_BLOCK' | 'REMOVE_DYNAMIC_BLOCK' | 'SHOW_MODAL' | 'DISPLAY_NOTIFICATION';
  /** Target element or area on the frontend where the command applies (e.g., a predefined slot ID). */
  targetElementId?: string;
  /**
   * Payload specific to the actionType.
   * For RENDER_DYNAMIC_BLOCK, this would include the block's definition.
   */
  payload: any; // Define more specific payload types per actionType
  /** Security context, e.g., required sandboxing level for JS. */
  securityContext?: 'SANDBOXED_IFRAME' | 'TRUSTED_WEB_COMPONENT' | 'NONE';
  /** Timestamp of command generation. */
  timestamp: string;
}

/**
 * Defines the structure of a UI block manifest as generated by a GMI.
 * This is part of the payload for RENDER_DYNAMIC_BLOCK.
 */
export interface DynamicUIBlockManifest {
  /** Unique identifier for this block type/instance. */
  blockId: string;
  /** User-friendly name or title for the block. */
  name: string;
  /** Description of the block's purpose or content. */
  description?: string;
  /**
   * Type of content: 'html_fragment', 'vue_component_options', 'simple_js_function', 'markdown'.
   * This informs the frontend renderer how to handle 'content'.
   */
  contentType: 'html_fragment' | 'vue_component_options_string' | 'simple_js_function_string' | 'markdown_string';
  /** Initial data or props for the block. */
  initialData?: Record<string, any>;
  /** Expected Tailwind CSS classes for the container, or specific style hints. */
  containerClasses?: string; // e.g., "p-4 bg-blue-100 rounded-lg"
   /**
   * If contentType is 'vue_component_options_string' or 'simple_js_function_string',
   * this defines the expected inputs (props) and outputs (events) for sandboxing.
   */
  interface?: {
    props?: Array<{ name: string, type: string, description?: string }>; // e.g. { name: 'count', type: 'number' }
    emits?: Array<{ name: string, payloadType?: string, description?: string }>; // e.g. { name: 'incremented', payloadType: 'number' }
  };
}

/**
 * The raw UI generation intent received from a GMI.
 */
export interface GMI_UIIntent {
  /** Identifier for the GMI proposing this UI change. */
  gmiInstanceId: string;
  /** Identifier for the persona that generated this intent. */
  personaId: string;
  /**
   * The proposed UI block manifest (defined by the GMI).
   * For 'CAN_GENERATE_UI_BLOCK_JS', this contains the definition.
   */
  manifest: DynamicUIBlockManifest;
  /**
   * The actual content string (e.g., JS code, Vue component options as a string, HTML snippet, Markdown).
   * This needs careful sanitization and sandboxed rendering.
   */
  contentString: string;
  /**
   * Optional. GMI's reasoning or prompt that led to this UI generation.
   * Useful for debugging or iterative refinement.
   */
  generationPrompt?: string;
  /**
   * Optional. Specific target area on the UI if the GMI has a notion of it.
   */
  targetPlacementHint?: string;
}


export interface IUIActionOrchestratorService {
  /**
   * Processes a UI generation intent from a GMI.
   * This involves validation, sanitization (conceptual), and transformation into safe FrontendUICommands.
   * @param intent The GMI_UIIntent object.
   * @param userId The ID of the user for whom this UI is being generated (for context/permissions).
   * @returns {Promise<FrontendUICommand[]>} A list of structured commands for the frontend.
   * @throws {Error} If the intent is invalid, unsafe, or cannot be processed.
   */
  processGMI_UIIntent(intent: GMI_UIIntent, userId: string): Promise<FrontendUICommand[]>;

  // Future methods might include:
  // - parseNaturalLanguageUIRequest(nlRequest: string, gmiContext: any): Promise<GMI_UIIntent>;
  // - validateUIBlockContent(content: string, contentType: string): Promise<{isValid: boolean, issues?: string[]}>;
}